import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import type React from "react";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "@fortawesome/fontawesome-free/css/brands.css";
import { Providers } from "@/app/providers";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "BRU",
	description: "Generated by hand",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<head>
			<link rel="icon" href="/favicon.ico" sizes="any"/>
			<link
				rel="apple-touch-icon"
				href="/favicon/apple-touch-icon.png"
				type="image/png"
				sizes="180x180"
			/>
			<title>Buildings 'R' Us</title>
		</head>
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
		<Providers>{children}</Providers>
			</body>
		</html>
	);
}
